version: '3.5'

services: 
    ella:
        build: ./
        container_name: ella
        volumes: 
            - ./:/usr/src/app
    postgres:
        image: postgres:13.2-alpine
        #alpine image is smaller than using postgres:latest, which is why we use it. 
        container_name: postgres
        restart: always
        volumes:
            - ./:/usr/src/app
        environment:
            - POSTGRES_USER=root
            - POSTGRES_DB=root
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 5432:5432
#After docker-compose up, run this command in the root folder, with the containers running: docker container exec -i $(docker-compose ps -q postgres) psql root < assa.sql